_BASE_: "Base-SOLOv2.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  SOLOV2:
    NUM_CLASSES: 4
DATASETS:
  TRAIN: ("ttpla_train",)
  TEST: ("ttpla_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 8
